# Generated by Django 5.1.4 on 2025-03-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyScan',
            fields=[
                ('Scanid', models.AutoField(primary_key=True, serialize=False)),
                ('apply_date', models.DateField()),
                ('booking_date', models.DateField()),
                ('pref_time', models.CharField(max_length=8)),
                ('Status', models.CharField(max_length=10)),
                ('apply_loc', models.CharField(max_length=20)),
                ('coupon_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commentsid', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.CharField(max_length=10)),
                ('Date', models.DateField()),
                ('User', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CounsellingBook',
            fields=[
                ('Counsid', models.AutoField(primary_key=True, serialize=False)),
                ('bookingdate', models.DateField()),
                ('Regdate', models.DateField()),
                ('timeslot', models.IntegerField()),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PatHealthRec',
            fields=[
                ('Recorded', models.AutoField(primary_key=True, serialize=False)),
                ('rec_det', models.IntegerField()),
                ('prev_hospital', models.CharField(max_length=30)),
                ('treat_file', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RegFreevig',
            fields=[
                ('Regid', models.AutoField(primary_key=True, serialize=False)),
                ('Regdate', models.DateField()),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
    ]
