# Generated by Django 5.1.4 on 2025-04-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatHealthRec',
        ),
    ]
