# Generated by Django 5.1.4 on 2025-04-24 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_rename_canctypeid_cancertype_id_and_more'),
        ('login', '0002_rename_mob_guest_mobile_and_more'),
        ('patient', '0002_delete_pathealthrec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyscan',
            old_name='coupon_no',
            new_name='coupon_number',
        ),
        migrations.RenameField(
            model_name='applyscan',
            old_name='Scanid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='commentsid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='counsellingbook',
            old_name='Regdate',
            new_name='Booking_date',
        ),
        migrations.RenameField(
            model_name='counsellingbook',
            old_name='bookingdate',
            new_name='Registration_date',
        ),
        migrations.RenameField(
            model_name='counsellingbook',
            old_name='timeslot',
            new_name='Times_lot',
        ),
        migrations.RenameField(
            model_name='counsellingbook',
            old_name='Counsid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='regfreevig',
            old_name='Regdate',
            new_name='Registration_date',
        ),
        migrations.RenameField(
            model_name='regfreevig',
            old_name='Regid',
            new_name='Registration_id',
        ),
        migrations.RemoveField(
            model_name='applyscan',
            name='apply_loc',
        ),
        migrations.RemoveField(
            model_name='applyscan',
            name='pref_time',
        ),
        migrations.AddField(
            model_name='applyscan',
            name='Apply_location',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applyscan',
            name='Patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.patient'),
        ),
        migrations.AddField(
            model_name='applyscan',
            name='Preferred_time',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='applyscan',
            name='Scan_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.scantype'),
        ),
        migrations.AddField(
            model_name='applyscan',
            name='scan_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.scancenter'),
        ),
        migrations.AddField(
            model_name='counsellingbook',
            name='patientId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.patient'),
        ),
        migrations.AddField(
            model_name='regfreevig',
            name='Patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.patient'),
        ),
        migrations.AlterField(
            model_name='applyscan',
            name='Status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='User',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comments',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='counsellingbook',
            name='Status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='regfreevig',
            name='Status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='PatHealthRec',
            fields=[
                ('Recorded', models.AutoField(primary_key=True, serialize=False)),
                ('Record_details', models.IntegerField()),
                ('Previous_hospital', models.CharField(max_length=30, null=True)),
                ('Treat_file', models.CharField(max_length=30, null=True)),
                ('Patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.patient')),
            ],
        ),
    ]
