# Generated by Django 5.1.4 on 2025-04-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_rename_coupon_no_applyscan_coupon_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyscan',
            old_name='Apply_location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='applyscan',
            old_name='Patient',
            new_name='patient',
        ),
        migrations.RemoveField(
            model_name='applyscan',
            name='apply_date',
        ),
        migrations.RemoveField(
            model_name='applyscan',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='applyscan',
            name='coupon_number',
        ),
        migrations.RemoveField(
            model_name='applyscan',
            name='scan_center',
        ),
        migrations.AddField(
            model_name='applyscan',
            name='Coupon',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='applyscan',
            name='Preferred_time',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='applyscan',
            name='Status',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='applyscan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='applyscan',
            name='Booking_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='applyscan',
            name='Scan_Center',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
