# Generated by Django 5.1.4 on 2025-05-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_rename_apply_location_applyscan_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathealthrec',
            old_name='Record_details',
            new_name='Record_detected',
        ),
    ]
