# Generated by Django 5.1.4 on 2025-05-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_rename_record_details_pathealthrec_record_detected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathealthrec',
            old_name='Record_detected',
            new_name='Records_Detected',
        ),
    ]
