# Generated by Django 5.1.4 on 2025-05-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_rename_record_detected_pathealthrec_records_detected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyscan',
            name='Location',
        ),
        migrations.AddField(
            model_name='applyscan',
            name='Amount',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
