# Generated by Django 5.1.4 on 2025-05-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0020_alter_dietarysupply_daily_serving_and_more'),
        ('patient', '0007_remove_applyscan_location_applyscan_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyscan',
            name='Amount',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='applyscan',
            name='Scan_Type',
        ),
        migrations.AddField(
            model_name='applyscan',
            name='Scan_Type',
            field=models.ManyToManyField(to='administrator.scantype'),
        ),
    ]
