# Generated by Django 5.1.4 on 2025-05-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_alter_applyscan_amount_remove_applyscan_scan_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyscan',
            name='Status',
            field=models.CharField(default='New', max_length=20),
        ),
    ]
