# Generated by Django 5.1.4 on 2025-05-23 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_alter_applyscan_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathealthrec',
            old_name='Records_Detected',
            new_name='Records_Details',
        ),
    ]
