# Generated by Django 5.1.4 on 2025-05-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_rename_records_detected_pathealthrec_records_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathealthrec',
            name='Records_Details',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pathealthrec',
            name='Treat_file',
            field=models.FileField(blank=True, null=True, upload_to='patient_photos/'),
        ),
    ]
