# Generated by Django 5.1.4 on 2025-05-23 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_alter_pathealthrec_records_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellingbook',
            name='Registration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
