# Generated by Django 5.1.4 on 2025-05-23 09:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_alter_counsellingbook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellingbook',
            name='Status',
            field=models.CharField(default='Pending', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='regfreevig',
            name='Registration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='regfreevig',
            name='Status',
            field=models.CharField(default='Pending', max_length=10, null=True),
        ),
    ]
