# Generated by Django 5.1.4 on 2025-05-23 14:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_patient_district'),
        ('patient', '0014_alter_counsellingbook_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='Patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.patient'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
