# Generated by Django 5.1.4 on 2025-05-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_remove_comments_user_comments_patient_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='comments',
        #     name='User',
        # ),
        migrations.AlterField(
            model_name='comments',
            name='comments',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
