# Generated by Django 5.1.4 on 2025-05-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_remove_comments_user_alter_comments_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='User',
        ),
    ]
