# Generated by Django 5.1.4 on 2025-05-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_remove_comments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyscan',
            name='Preferred_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
