# Generated by Django 5.1.4 on 2025-05-24 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0020_alter_dietarysupply_daily_serving_and_more'),
        ('patient', '0018_alter_applyscan_preferred_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyscan',
            name='Scan_Center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.scancenter'),
        ),
    ]
