# Generated by Django 5.1.4 on 2025-05-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_alter_applyscan_scan_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='regfreevig',
            name='Coupon',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
