# Generated by Django 5.1.4 on 2025-05-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_regfreevig_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regfreevig',
            name='Coupon',
        ),
        migrations.AddField(
            model_name='counsellingbook',
            name='Coupon',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
