# Generated by Django 5.1.4 on 2025-05-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0022_alter_counsellingbook_times_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='regfreevig',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regfreevig',
            name='Age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regfreevig',
            name='Full_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='regfreevig',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='regfreevig',
            name='Phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
