# Generated by Django 5.1.4 on 2025-05-25 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0020_alter_dietarysupply_daily_serving_and_more'),
        ('patient', '0023_regfreevig_address_regfreevig_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellingbook',
            name='coun_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.councenter'),
        ),
    ]
