# Generated by Django 5.1.4 on 2025-03-13 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='HairDonationCriteria',
            fields=[
                ('criteria_id', models.AutoField(primary_key=True, serialize=False)),
                ('criteria', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('don_date', models.DateField()),
                ('transaction_type', models.CharField(max_length=10)),
                ('card_no', models.IntegerField()),
                ('bank', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.guest')),
            ],
        ),
        migrations.CreateModel(
            name='HairDonation',
            fields=[
                ('h_don_id', models.AutoField(primary_key=True, serialize=False)),
                ('apply_date', models.DateField()),
                ('hair_type', models.CharField(max_length=20)),
                ('h_image', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.guest')),
            ],
        ),
    ]
