# Generated by Django 5.1.4 on 2025-03-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HairDonationCriteria',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='amount',
            new_name='Amount',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='bank',
            new_name='Bank',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='card_no',
            new_name='Cardno',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='guest',
            new_name='Guestid',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donation_id',
            new_name='donationid',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='transaction_type',
            new_name='transactiontype',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='guest_id',
            new_name='Guestid',
        ),
        migrations.RenameField(
            model_name='hairdonation',
            old_name='guest',
            new_name='Guestid',
        ),
        migrations.RenameField(
            model_name='hairdonation',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='hairdonation',
            old_name='apply_date',
            new_name='applydate',
        ),
        migrations.RenameField(
            model_name='hairdonation',
            old_name='h_don_id',
            new_name='hDonID',
        ),
        migrations.RenameField(
            model_name='hairdonation',
            old_name='hair_type',
            new_name='hairtype',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='name',
        ),
        migrations.AddField(
            model_name='guest',
            name='Address',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='Distid',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='Mob',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='Phone',
            field=models.BigIntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='Pwd',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='Regdate',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='Staus',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='Umane',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='Name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
