# Generated by Django 5.1.4 on 2025-03-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_delete_hairdonationcriteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='Distid',
            field=models.IntegerField(default=1),
        ),
    ]
