# Generated by Django 5.1.4 on 2025-03-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_alter_guest_distid'),
    ]

    operations = [
    ]
