# Generated by Django 5.1.4 on 2025-04-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_auto_20250317_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairdonation',
            name='Guestid',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='HairDonation',
        ),
    ]
