# Generated by Django 5.1.4 on 2025-04-24 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest', '0005_remove_hairdonation_guestid_delete_donation_and_more'),
        ('login', '0002_rename_mob_guest_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.IntegerField()),
                ('Donation_date', models.DateField()),
                ('Transaction_type', models.CharField(max_length=10)),
                ('Card_number', models.IntegerField()),
                ('Bank', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=10)),
                ('Guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.guest')),
            ],
        ),
        migrations.CreateModel(
            name='HairDonation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Apply_date', models.DateField()),
                ('Hair_type', models.CharField(max_length=20)),
                ('Hair_image', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=10)),
                ('Guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.guest')),
            ],
        ),
    ]
