# Generated by Django 5.1.4 on 2025-05-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairdonation',
            name='Hair_image',
            field=models.ImageField(upload_to='hair_images/'),
        ),
        migrations.AlterField(
            model_name='hairdonation',
            name='Hair_type',
            field=models.CharField(choices=[('Straight', 'Straight'), ('Wavy', 'Wavy'), ('Curly', 'Curly'), ('Coily', 'Coily')], max_length=20),
        ),
    ]
