# Generated by Django 5.1.4 on 2025-05-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0007_alter_hairdonation_hair_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairdonation',
            name='Hair_image',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hairdonation',
            name='Hair_type',
            field=models.CharField(max_length=20),
        ),
    ]
