# Generated by Django 5.1.4 on 2025-05-27 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0009_alter_hairdonation_hair_image_and_more'),
        ('login', '0003_alter_patient_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairdonation',
            name='Guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.guest'),
        ),
    ]
