# Generated by Django 5.1.4 on 2025-05-28 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0010_alter_hairdonation_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='Payment_status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='Bank',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='Card_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='Donation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='Status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='Transaction_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='hairdonation',
            name='Apply_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
