# Generated by Django 5.1.4 on 2025-03-17 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('u_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Pwd', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CancerType',
            fields=[
                ('cancTypeid', models.AutoField(primary_key=True, serialize=False)),
                ('cancertype', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CounCenter',
            fields=[
                ('coun_centreid', models.AutoField(primary_key=True, serialize=False)),
                ('coun_center', models.CharField(max_length=30)),
                ('Descr', models.CharField(max_length=150)),
                ('Address', models.CharField(max_length=150)),
                ('Doctor', models.CharField(max_length=20)),
                ('Phone', models.BigIntegerField()),
                ('Mob', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DietarySupply',
            fields=[
                ('diet_supplyid', models.AutoField(primary_key=True, serialize=False)),
                ('food_gp', models.CharField(max_length=10)),
                ('sugg_daily_serv', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DietaryTip',
            fields=[
                ('Dietid', models.AutoField(primary_key=True, serialize=False)),
                ('diet_tips', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('eventTitle', models.CharField(max_length=10)),
                ('Descr', models.CharField(max_length=10)),
                ('Location', models.CharField(max_length=20)),
                ('eventdate', models.DateField()),
                ('ev_time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='GuideLines',
            fields=[
                ('guId', models.AutoField(primary_key=True, serialize=False)),
                ('Guides', models.CharField(max_length=10)),
                ('added_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HairDonCriteria',
            fields=[
                ('criteriaid', models.AutoField(primary_key=True, serialize=False)),
                ('Criteria', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MedServices',
            fields=[
                ('mserv_id', models.AutoField(primary_key=True, serialize=False)),
                ('med_service', models.CharField(max_length=10)),
                ('Descr', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ScanCenter',
            fields=[
                ('scan_cenid', models.AutoField(primary_key=True, serialize=False)),
                ('Center', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=150)),
                ('Distid', models.IntegerField()),
                ('Phone', models.BigIntegerField()),
                ('Mob', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Regdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ScanType',
            fields=[
                ('scTypeid', models.AutoField(primary_key=True, serialize=False)),
                ('Scantype', models.CharField(max_length=30)),
                ('Amount', models.IntegerField()),
                ('Discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('Stateid', models.AutoField(primary_key=True, serialize=False)),
                ('State', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dist',
            fields=[
                ('Distid', models.AutoField(primary_key=True, serialize=False)),
                ('Dist', models.CharField(max_length=20)),
                ('Stateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.state')),
            ],
        ),
    ]
