# Generated by Django 5.1.4 on 2025-03-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scancenter',
            name='Distid',
            field=models.IntegerField(default=1),
        ),
    ]
