# Generated by Django 5.1.4 on 2025-04-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_scancenter_distid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RenameField(
            model_name='cancertype',
            old_name='cancTypeid',
            new_name='cancerTypeid',
        ),
        migrations.AlterField(
            model_name='cancertype',
            name='cancertype',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='councenter',
            name='Address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='councenter',
            name='Descr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='councenter',
            name='Doctor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='councenter',
            name='coun_center',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dietarysupply',
            name='food_gp',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dietarysupply',
            name='sugg_daily_serv',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietarytip',
            name='diet_tips',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dist',
            name='Dist',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='Descr',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='Location',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='ev_time',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventTitle',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='guidelines',
            name='Guides',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hairdoncriteria',
            name='Criteria',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medservices',
            name='Descr',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medservices',
            name='Status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medservices',
            name='med_service',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scancenter',
            name='Address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='scancenter',
            name='Center',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='scancenter',
            name='Distid',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='scantype',
            name='Scantype',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='State',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
