# Generated by Django 5.1.4 on 2025-04-24 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_delete_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancertype',
            old_name='cancerTypeid',
            new_name='cancTypeid',
        ),
        migrations.RenameField(
            model_name='medservices',
            old_name='Descr',
            new_name='Description',
        ),
    ]
