# Generated by Django 5.1.4 on 2025-04-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_rename_cancertypeid_cancertype_canctypeid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medservices',
            old_name='mserv_id',
            new_name='id',
        ),
    ]
