# Generated by Django 5.1.4 on 2025-04-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_rename_mserv_id_medservices_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guidelines',
            old_name='guId',
            new_name='id',
        ),
    ]
