# Generated by Django 5.1.4 on 2025-04-24 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_rename_guid_guidelines_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancertype',
            old_name='cancTypeid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='councenter',
            old_name='Descr',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='councenter',
            old_name='Mob',
            new_name='Mobile',
        ),
        migrations.RenameField(
            model_name='councenter',
            old_name='coun_center',
            new_name='counsling_center',
        ),
        migrations.RenameField(
            model_name='councenter',
            old_name='coun_centreid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='dietarysupply',
            old_name='sugg_daily_serv',
            new_name='daily_serving',
        ),
        migrations.RenameField(
            model_name='dietarysupply',
            old_name='food_gp',
            new_name='food_group',
        ),
        migrations.RenameField(
            model_name='dietarysupply',
            old_name='diet_supplyid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='dietarytip',
            old_name='Dietid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='dist',
            old_name='Dist',
            new_name='District',
        ),
        migrations.RenameField(
            model_name='dist',
            old_name='Stateid',
            new_name='State',
        ),
        migrations.RenameField(
            model_name='dist',
            old_name='Distid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='eventdate',
            new_name='Event_date',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='eventTitle',
            new_name='Event_title',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='ev_time',
            new_name='event_time',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='eventId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='hairdoncriteria',
            old_name='criteriaid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='medservices',
            old_name='med_service',
            new_name='medical_service',
        ),
        migrations.RenameField(
            model_name='scancenter',
            old_name='Mob',
            new_name='Mobile',
        ),
        migrations.RenameField(
            model_name='scancenter',
            old_name='Regdate',
            new_name='Registration_date',
        ),
        migrations.RenameField(
            model_name='scancenter',
            old_name='scan_cenid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='scantype',
            old_name='scTypeid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='Stateid',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='scancenter',
            name='Distid',
        ),
        migrations.AddField(
            model_name='scancenter',
            name='District',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.state'),
        ),
    ]
