# Generated by Django 5.1.4 on 2025-05-15 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_rename_canctypeid_cancertype_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='Descr',
            new_name='Description',
        ),
    ]
