# Generated by Django 5.1.4 on 2025-05-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_rename_descr_events_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scantype',
            old_name='Scantype',
            new_name='Scan_Type',
        ),
    ]
