# Generated by Django 5.1.4 on 2025-05-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_rename_scantype_scantype_scan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_time',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
