# Generated by Django 5.1.4 on 2025-05-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_alter_events_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='Description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='Event_title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
