# Generated by Django 5.1.4 on 2025-05-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_alter_events_description_alter_events_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='Description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
