# Generated by Django 5.1.4 on 2025-05-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_alter_events_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidelines',
            name='Guides',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
