# Generated by Django 5.1.4 on 2025-05-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_alter_scancenter_district_alter_scancenter_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councenter',
            name='Address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='councenter',
            name='Description',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='councenter',
            name='Doctor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='councenter',
            name='counsling_center',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
