# Generated by Django 5.1.4 on 2025-05-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_alter_councenter_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councenter',
            name='Mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='councenter',
            name='Phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
