# Generated by Django 5.1.4 on 2025-05-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_alter_councenter_mobile_alter_councenter_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medservices',
            name='Description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medservices',
            name='medical_service',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
