# Generated by Django 5.1.4 on 2025-05-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_alter_medservices_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairdoncriteria',
            name='Criteria',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
