# Generated by Django 5.1.4 on 2025-05-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_alter_hairdoncriteria_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietarytip',
            name='diet_tips',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
