# Generated by Django 5.1.4 on 2025-02-12 12:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('Guestid', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Address', models.TextField(max_length=150)),
                ('Distid', models.IntegerField()),
                ('Regdate', models.DateField(default=django.utils.timezone.now)),
                ('Phone', models.BigIntegerField()),
                ('Mob', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=20)),
                ('Uname', models.CharField(max_length=10, unique=True)),
                ('Pwd', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=10)),
                ('Login', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Patientid', models.AutoField(primary_key=True, serialize=False)),
                ('Patname', models.CharField(max_length=30)),
                ('Address', models.TextField(max_length=150)),
                ('Distid', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Photo', models.ImageField(upload_to='patient_photos/')),
                ('cancTypeid', models.IntegerField()),
                ('DetectedDate', models.DateField()),
                ('DetectedHospital', models.CharField(max_length=50)),
                ('Consult_Drname', models.CharField(max_length=50)),
                ('No_months_yr', models.IntegerField()),
                ('Stage', models.CharField(max_length=30)),
                ('Regdate', models.DateField(default=django.utils.timezone.now)),
                ('Status', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
                ('Mob', models.BigIntegerField()),
                ('Username', models.CharField(max_length=10, unique=True)),
                ('Pwd', models.CharField(max_length=10)),
                ('Login', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=20)),
                ('Login', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('volunteerId', models.AutoField(primary_key=True, serialize=False)),
                ('Regdate', models.DateField(default=django.utils.timezone.now)),
                ('apply_area', models.CharField(max_length=20)),
                ('want_loc', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=10)),
                ('Guestid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.guest')),
                ('Login', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
