# Generated by Django 5.1.4 on 2025-04-24 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_rename_canctypeid_cancertype_id_and_more'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='Mob',
            new_name='Mobile',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='Regdate',
            new_name='Registration_date',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='Guestid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Consult_Drname',
            new_name='Consult_Doctor',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='DetectedDate',
            new_name='Detected_Date',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='DetectedHospital',
            new_name='Detected_Hospital',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Mob',
            new_name='Mobile',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Patname',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Distid',
            new_name='No_months_per_year',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Regdate',
            new_name='Registration_date',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Patientid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='apply_area',
            new_name='Apply_area',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='Guestid',
            new_name='Guest',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='want_loc',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='Regdate',
            new_name='Registration_date',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='volunteerId',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='Distid',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='Pwd',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='Uname',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='No_months_yr',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Pwd',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Username',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='cancTypeid',
        ),
        migrations.AddField(
            model_name='guest',
            name='District',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.dist'),
        ),
        migrations.AddField(
            model_name='patient',
            name='Cancer_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.cancertype'),
        ),
        migrations.AddField(
            model_name='patient',
            name='District',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.dist'),
        ),
    ]
