# Generated by Django 5.1.4 on 2025-04-25 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_rename_canctypeid_cancertype_id_and_more'),
        ('login', '0002_rename_mob_guest_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='District',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district', to='administrator.dist'),
        ),
    ]
