# Generated by Django 5.1.4 on 2025-03-17 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('Guestid', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=150)),
                ('Distid', models.IntegerField()),
                ('Regdate', models.DateField()),
                ('Phone', models.BigIntegerField()),
                ('Mob', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Umane', models.CharField(max_length=10)),
                ('Pwd', models.CharField(max_length=4)),
                ('Staus', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PatientReg',
            fields=[
                ('Patientid', models.AutoField(primary_key=True, serialize=False)),
                ('Patname', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=150)),
                ('Distid', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Photo', models.CharField(max_length=10)),
                ('DetectedDate', models.DateField()),
                ('DetectedHospital', models.CharField(max_length=10)),
                ('Consult_Drname', models.CharField(max_length=10)),
                ('No_months_yr', models.IntegerField()),
                ('Stage', models.CharField(max_length=30)),
                ('Regdate', models.DateField()),
                ('Status', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Mob', models.BigIntegerField()),
                ('Username', models.CharField(max_length=10)),
                ('Pwd', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerReg',
            fields=[
                ('volunteerId', models.AutoField(primary_key=True, serialize=False)),
                ('Regdate', models.DateField()),
                ('apply_area', models.CharField(max_length=20)),
                ('want_loc', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=10)),
                ('Guestid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.guest')),
            ],
        ),
    ]
